# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  sf_guard_plugin:
    remember_key_expiration_age:  2592000
    remember_cookie_name:         myAppRememberMe
    #check_password_callable: [myLDAP, checkLDAPPassword]
    success_signin_url:      @homepage
    #success_signout_url:     module/action