<?php


/**
 * Skeleton subclass for performing query and update operations on the 'image_comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 24 15:47:54 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ImageCommentPeer extends BaseImageCommentPeer {

    public static function fetchCommentsForImage($imageId){
        $c = new Criteria();
        $c->add(ImageCommentPeer::IMAGE_ID, $imageId);
        $c->addAscendingOrderByColumn(CREATED_AT);
        $v = ImageCommentPeer::doSelect($c);
        return $v;
    }

    public static function fetchCommentsForClients($imageId){
        $c = new Criteria();
        $c->add(ImageCommentPeer::IMAGE_ID, $imageId);
        $c->add(ImageCommentPeer::CREATOR_IS, 'client');
        $c->add(ImageCommentPeer::CREATOR_IS, 'cm');
        $c->addAscendingOrderByColumn(CREATED_AT);
        $v = ImageCommentPeer::doSelect($c);
        return $v;
    }

} // ImageCommentPeer
