<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_user_project' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep 24 16:16:29 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfGuardPlugin.lib.model
 */
class sfGuardUserProjectPeer extends BasesfGuardUserProjectPeer {

} // sfGuardUserProjectPeer
