<?php


/**
 * Skeleton subclass for performing query and update operations on the 'image_mark' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Sep 28 15:04:40 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ImageMarkPeer extends BaseImageMarkPeer {

    public static function fetchMarksForImage($imageId){
        $c = new Criteria();
        $c->add(ImageMarkPeer::IMAGE_ID, $imageId);
        $c->addDescendingOrderByColumn(ImageMarkPeer::IMAGE_ID);
        $v = ImageMarkPeer::doSelect($c);
        return $v;
    }

} // ImageMarkPeer
