<?php


/**
 * Skeleton subclass for performing query and update operations on the 'sf_guard_group_project' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep 26 15:33:49 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class sfGuardGroupProjectPeer extends BasesfGuardGroupProjectPeer {

    public static function retrieveClientForGroupById($groupId){
        $c = new Criteria();
        $c->add(sfGuardGroupProjectPeer::GROUP_ID, $groupId);
        $c->addDescendingOrderByColumn(sfGuardGroupProjectPeer::GROUP_ID);
        $v = sfGuardGroupProjectPeer::doSelect($c);
        return $v;
    }

} // sfGuardGroupProjectPeer
