<?php


/**
 * Skeleton subclass for performing query and update operations on the 'ldap_server' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Jun 28 05:46:05 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LDAPServerPeer extends BaseLDAPServerPeer {

	public static function getById($id){
		$c = new Criteria();
		$c->add(LDAPServerPeer::ID, $id);
		$v = LDAPServerPeer::doSelect($c);
		return $v[0];
	}

	public static function getByName($name){
		$c = new Criteria();
		$c->add(LDAPServerPeer::NAME, $name);
		$v = LDAPServerPeer::doSelect($c);
		return $v[0];
	}

	public static function getActive(){
		$c = new Criteria();
		$c->add(LDAPServerPeer::STATUS, 1);
		$v = LDAPServerPeer::doSelect($c);
		return $v;
	}
} // LDAPServerPeer
