<?php


/**
 * Skeleton subclass for representing a row from the 'sf_guard_group_project' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep 26 15:33:49 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class sfGuardGroupProject extends BasesfGuardGroupProject {

} // sfGuardGroupProject
